# Custom Language File for Launcher Customizer

[ejs.app]
title = "Helios Launcher"

[ejs.landing]
mediaGitHubURL = "https://rebuildbruxelle.free.nf/"
mediaTwitterURL = "https://x.com/BuildBruxelles"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/sGvknfGKMk"

[ejs.settings]
sourceGithubLink = "https://github.com/NoryNinin/BruxellesLauncher"
supportLink = "https://github.com/NoryNinin/BruxellesLauncher/issues"

[ejs.welcome]
welcomeHeader = "Bienvenue sur Bruxelles"
welcomeDescription = "Notre but re crée la ville de Bruxelles, la capital de la Belgique sur Minecraft a l'échelle 1:1"
welcomeDescCTA = "prêt(e) a Jouer ?"
